import { Course } from './types';

export const csTemplate: Course[] = [
  {
    id: 'cs101',
    name: 'Calculus I',
    year: 1,
    status: 'completed',
    rating: null,
    review: null,
    resources: [],
    prof_review: null,
  },
  {
    id: 'cs102',
    name: 'Introduction to Programming',
    year: 1,
    status: 'completed',
    rating: null,
    review: null,
    resources: [],
    prof_review: null,
  },
  {
    id: 'cs103',
    name: 'Data Structures',
    year: 2,
    status: 'completed',
    rating: null,
    review: null,
    resources: [],
    prof_review: null,
  },
  {
    id: 'cs104',
    name: 'Algorithms',
    year: 2,
    status: 'completed',
    rating: null,
    review: null,
    resources: [],
    prof_review: null,
  },
  {
    id: 'cs105',
    name: 'Object-Oriented Programming',
    year: 2,
    status: 'completed',
    rating: null,
    review: null,
    resources: [],
    prof_review: null,
  },
  {
    id: 'cs106',
    name: 'Operating Systems',
    year: 3,
    status: 'completed',
    rating: null,
    review: null,
    resources: [],
    prof_review: null,
  },
  {
    id: 'cs107',
    name: 'Database Systems',
    year: 3,
    status: 'completed',
    rating: null,
    review: null,
    resources: [],
    prof_review: null,
  },
  {
    id: 'cs108',
    name: 'Computer Networks',
    year: 3,
    status: 'completed',
    rating: null,
    review: null,
    resources: [],
    prof_review: null,
  },
  {
    id: 'cs109',
    name: 'Machine Learning',
    year: 4,
    status: 'locked',
    rating: null,
    review: null,
    resources: [],
    prof_review: null,
  },
  {
    id: 'cs110',
    name: 'Artificial Intelligence',
    year: 4,
    status: 'locked',
    rating: null,
    review: null,
    resources: [],
    prof_review: null,
  },
];

export const automationTemplate: Course[] = [
  {
    id: 'auto101',
    name: 'Circuit Analysis',
    year: 1,
    status: 'completed',
    rating: null,
    review: null,
    resources: [],
    prof_review: null,
  },
  {
    id: 'auto102',
    name: 'Digital Logic Design',
    year: 1,
    status: 'completed',
    rating: null,
    review: null,
    resources: [],
    prof_review: null,
  },
  {
    id: 'auto103',
    name: 'Signals and Systems',
    year: 2,
    status: 'completed',
    rating: null,
    review: null,
    resources: [],
    prof_review: null,
  },
  {
    id: 'auto104',
    name: 'Control Theory',
    year: 2,
    status: 'completed',
    rating: null,
    review: null,
    resources: [],
    prof_review: null,
  },
  {
    id: 'auto105',
    name: 'PLC Programming',
    year: 2,
    status: 'completed',
    rating: null,
    review: null,
    resources: [],
    prof_review: null,
  },
  {
    id: 'auto106',
    name: 'Industrial Automation',
    year: 3,
    status: 'completed',
    rating: null,
    review: null,
    resources: [],
    prof_review: null,
  },
  {
    id: 'auto107',
    name: 'Robotics',
    year: 3,
    status: 'completed',
    rating: null,
    review: null,
    resources: [],
    prof_review: null,
  },
  {
    id: 'auto108',
    name: 'SCADA Systems',
    year: 3,
    status: 'completed',
    rating: null,
    review: null,
    resources: [],
    prof_review: null,
  },
  {
    id: 'auto109',
    name: 'Advanced Control Systems',
    year: 4,
    status: 'locked',
    rating: null,
    review: null,
    resources: [],
    prof_review: null,
  },
  {
    id: 'auto110',
    name: 'Smart Manufacturing',
    year: 4,
    status: 'locked',
    rating: null,
    review: null,
    resources: [],
    prof_review: null,
  },
];

export const blankTemplate: Course[] = [];

